apiVersion: apps/v1
kind: Deployment
metadata:
  name: upg-loadme
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upg-loadme
  template:
    metadata:
      name: upg-loadme
      labels:
        app: upg-loadme
    spec:
      tolerations:
        - key: "critical"
          operator: "Equal"
          value: "sch"
          effect: "NoSchedule"
      containers:
        - name: upg-loadme
          image: 485517222763.dkr.ecr.ap-south-1.amazonaws.com/capstone:tag
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 1
              memory: 1Gi
            limits:
              cpu: 1
              memory: 1Gi
          livenessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: upg-loadme
spec:
  selector:
    app: upg-loadme
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: LoadBalancer
